<?php

namespace App\Controllers\Admin;

use App\Controllers\BaseController;
use App\Services\BookingService;
use App\Services\SlotService;
use RuntimeException;

class BookingController extends BaseController
{
    private function detailRow(int $id): ?array { return db_connect()->table('bookings b')->select('b.*,c.name customer_name,c.phone customer_phone,s.name service_name,s.duration_minutes,st.name stylist_name')->join('customers c','c.id=b.customer_id')->join('services s','s.id=b.service_id')->join('stylists st','st.id=b.stylist_id')->where('b.id',$id)->get()->getRowArray(); }
    public function index(){ $db=db_connect(); $builder=$db->table('bookings b')->select('b.*,c.name customer_name,s.name service_name,st.name stylist_name')->join('customers c','c.id=b.customer_id')->join('services s','s.id=b.service_id')->join('stylists st','st.id=b.stylist_id'); if($this->request->getGet('status'))$builder->where('b.status',$this->request->getGet('status')); if($this->request->getGet('date'))$builder->where('b.booking_date',$this->request->getGet('date')); if($this->request->getGet('stylist_id'))$builder->where('b.stylist_id',$this->request->getGet('stylist_id')); return view('admin/bookings/index',['bookings'=>$builder->orderBy('b.booking_date','DESC')->orderBy('b.start_time','DESC')->get()->getResultArray(),'stylists'=>$db->table('stylists')->where('is_active',1)->get()->getResultArray()]); }
    public function pending(){ $_GET['status']='pending_verification'; return $this->index(); }
    public function schedule(){ $date=$this->request->getGet('date')?:date('Y-m-d'); $rows=db_connect()->table('bookings b')->select('b.*,c.name customer_name,s.name service_name,st.name stylist_name')->join('customers c','c.id=b.customer_id')->join('services s','s.id=b.service_id')->join('stylists st','st.id=b.stylist_id')->where('b.booking_date',$date)->whereIn('b.status',['pending_verification','accepted','completed'])->orderBy('b.start_time')->get()->getResultArray(); return view('admin/bookings/schedule',['bookings'=>$rows,'date'=>$date]); }
    public function walkin(){ $db=db_connect(); if($this->request->getMethod()==='POST'){ try{ $customerId=$this->request->getPost('customer_id'); if(!$customerId){$now=date('Y-m-d H:i:s');$db->table('customers')->insert(['name'=>$this->request->getPost('customer_name'),'phone'=>$this->request->getPost('customer_phone'),'created_at'=>$now,'updated_at'=>$now]);$customerId=$db->insertID();} $id=(new BookingService())->createBooking(['customer_id'=>$customerId,'service_id'=>$this->request->getPost('service_id'),'stylist_id'=>$this->request->getPost('stylist_id'),'booking_date'=>$this->request->getPost('booking_date'),'start_time'=>$this->request->getPost('start_time'),'notes'=>$this->request->getPost('notes'),'source'=>'walkin','created_by'=>session('user_id')]); return redirect()->to('/admin/booking/'.$id)->with('success','Booking walk-in berhasil dibuat.'); }catch(RuntimeException $e){return redirect()->back()->withInput()->with('error',$e->getMessage());}} return view('admin/bookings/walkin',['services'=>$db->table('services')->where('is_active',1)->get()->getResultArray(),'stylists'=>$db->table('stylists')->where('is_active',1)->get()->getResultArray(),'customers'=>$db->table('customers')->orderBy('name')->get()->getResultArray()]); }
    public function slots(){ return $this->response->setJSON((new SlotService())->generateAvailableSlots((int)$this->request->getGet('service_id'),(int)$this->request->getGet('stylist_id'),(string)$this->request->getGet('date'))); }
    public function detail(int $id){ $row=$this->detailRow($id); if(!$row)return redirect()->to('/admin/booking')->with('error','Booking tidak ditemukan.'); $logs=(new \App\Models\BookingLogModel())->forBooking($id); return view('admin/bookings/detail',['booking'=>$row,'logs'=>$logs]); }
    public function accept(int $id){ try{(new BookingService())->accept($id,(int)session('user_id'));return redirect()->to('/admin/booking/'.$id)->with('success','Booking diterima. Gunakan template WhatsApp manual untuk menghubungi pelanggan.');}catch(RuntimeException $e){return redirect()->back()->with('error',$e->getMessage());} }
    public function reject(int $id){ try{(new BookingService())->reject($id,(int)session('user_id'),$this->request->getPost('rejection_reason'));return redirect()->to('/admin/booking/'.$id)->with('success','Booking ditolak dan slot dilepas. Gunakan template WhatsApp manual untuk menghubungi pelanggan.');}catch(RuntimeException $e){return redirect()->back()->with('error',$e->getMessage());} }
    public function cancel(int $id){ try{(new BookingService())->cancel($id,(int)session('user_id'),false);return redirect()->to('/admin/booking/'.$id)->with('success','Booking dibatalkan dan slot dilepas.');}catch(RuntimeException $e){return redirect()->back()->with('error',$e->getMessage());} }
    public function complete(int $id){ try{(new BookingService())->complete($id,(int)session('user_id'));return redirect()->to('/admin/booking/'.$id)->with('success','Booking selesai dan transaksi otomatis dibuat.');}catch(RuntimeException $e){return redirect()->back()->with('error',$e->getMessage());} }
    public function markWaSent(int $id){ $db=db_connect(); $db->table('bookings')->where('id',$id)->update(['wa_notified_at'=>date('Y-m-d H:i:s'),'wa_notified_by'=>session('user_id'),'updated_at'=>date('Y-m-d H:i:s')]); $b=$this->detailRow($id); $db->table('notification_logs')->insert(['booking_id'=>$id,'channel'=>'whatsapp_manual','event_type'=>'manual_marked_sent','recipient'=>$b['customer_phone']??'','message'=>'Admin/Pemilik menandai WA sudah dikirim manual.','status'=>'manual_marked_sent','created_at'=>date('Y-m-d H:i:s')]); return redirect()->back()->with('success','WA ditandai sudah dikirim manual.'); }
}
