<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class DropStylistArtifacts extends Migration
{
    public function up()
    {
        $db = $this->db;
        $dbName = $db->getDatabase();

        // Drop FKs on bookings.stylist_id and booking_slots.stylist_id
        // (constraint names are MySQL-autogenerated so look them up).
        foreach (['bookings', 'booking_slots'] as $table) {
            $fields = $db->getFieldNames($table);
            if (! in_array('stylist_id', $fields, true)) {
                continue;
            }
            $rows = $db->query(
                'SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
                 WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?
                   AND REFERENCED_TABLE_NAME IS NOT NULL',
                [$dbName, $table, 'stylist_id']
            )->getResultArray();
            foreach ($rows as $r) {
                $db->query("ALTER TABLE `{$table}` DROP FOREIGN KEY `{$r['CONSTRAINT_NAME']}`");
            }
            // Drop column (also removes its plain index if any).
            $this->forge->dropColumn($table, 'stylist_id');
        }

        // Drop child table first (FK to stylists), then parent.
        $this->forge->dropTable('stylist_schedules', true);
        $this->forge->dropTable('stylists', true);
    }

    public function down()
    {
        // One-way removal; restore via baseline migration if ever needed.
    }
}
